version: "3"
include:
  - proxy.yaml
x-env_file: &env_file
  env_file:
    - .env
x-restart: &restart
  restart: on-failure
services:
  db:
    image: mysql:8
    <<: [*env_file, *restart]
    networks:
      backend:
        ipv4_address: 172.20.0.10
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%"
  web:
    depends_on:
      - db
    container_name: "web"
    build:
      context: .
      dockerfile: Dockerfile.python

    <<: [*env_file, *restart]
    networks:
      backend:
        ipv4_address: 172.20.0.5
    environment:
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=db